import '../../components/header/header';
import '../../components/container/container';
import '../../components/banner/banner';
import '../../components/advantages/advantages';
import '../../components/rooms/rooms';
import '../../components/reviews/reviews';
import '../../components/map/map';
import '../../components/footer/footer';
import '../../components/carousel-buttons/carousel-buttons';